apiVersion: v1
kind: Service
metadata:
  name: kh-headless-svc
spec:
  clusterIP: None # clusterIP must be None to create a headless service
  selector:
    job-name: kh-finetune-gemma-7b-it-job # must match Job name
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kh-finetune-gemma-7b-it-job
  namespace: ml-team
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: finetune-job
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: "35Gi"
        cluster-autoscaler.kubernetes.io/consume-provisioning-request: kh-a3-job
        cluster-autoscaler.kubernetes.io/provisioning-class-name: "queued-provisioning.gke.io"
    spec:
      subdomain: kh-headless-svc
      serviceAccountName: ray-worker
      terminationGracePeriodSeconds: 600
      containers:
      - name: gpu-job
        imagePullPolicy: Always 
        image: us-docker.pkg.dev/gkebatchexpce3c8dcb/llm/finetune:v0.1.44-nq-acc
        ports:
        - containerPort: 29500
        securityContext:
          privileged: true
        resources:
          requests:
            nvidia.com/gpu: "8"
          limits:
            nvidia.com/gpu: "8"
        # command: ["sleep", "infinity"]
        # command: ["python", "/workspace/fine_tune.py"]
        command:
          - bash
          - -c
          - |
            accelerate launch \
            --config_file fsdp_config.yaml \
            --debug \
            --main_process_ip kh-finetune-gemma-7b-it-job-0.kh-headless-svc \
            --main_process_port 29500 \
            --machine_rank ${JOB_COMPLETION_INDEX} \
            --num_processes 8 \
            --num_machines 1 \
            fine_tune.py
        env:
        - name: "CUDA_VISIBLE_DEVICES"
          value: "0"
        # - name: "MLFLOW_TRACKING_URI"
        #   value: "http://mlflow.ml-tools:5000"
        - name: "EXPERIMENT"
          value: "gemma-nq-acc"
        - name: "MLFLOW_ENABLE"
          value: "true"
        - name: "MLFLOW_TRACKING_URI"
          value: "http://mlflow-tracking-service.ml-tools:5000"
        - name: "MLFLOW_ENABLE_SYSTEM_METRICS_LOGGING"
          value: "true"
        - name: "TRAINING_DATASET_BUCKET"
          value: "kh-finetune-ds"
        - name: "TRAINING_DATASET_PATH"
          value: "/new-format/dataset-it/training"
        - name: MODEL_NAME
          value: "google/gemma-1.1-7b-it"
        - name: NEW_MODEL
          value: "gemma-ft"
        - name: MODEL_PATH
          value: "/model-data/a3/model-0.1.44-7-nq-acc"
        - name: EPOCHS
          value: "1"
        - name: NCCL_DEBUG
          value: "INFO"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /model-data
          readOnly: false
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: kr-finetune
            mountOptions: "implicit-dirs"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-h100-80gb
        resource-model: h100
      restartPolicy: OnFailure
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "ondemand"
        value: "true"
        operator: "Equal"
        effect: "NoSchedule"
      - key: "on-demand"
        value: "true"
        operator: "Equal"
        effect: "NoSchedule"        