apiVersion: v1
kind: Service
metadata:
  name: kr-headless-svc
spec:
  clusterIP: None # clusterIP must be None to create a headless service
  selector:
    job-name: kr-finetune-gemma-7b-it-job # must match Job name
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kr-finetune-gemma-7b-it-job
  namespace: ml-team  
spec:
  backoffLimit: 20
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: finetune-job
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: "35Gi"
        cluster-autoscaler.kubernetes.io/consume-provisioning-request: a2-job
        cluster-autoscaler.kubernetes.io/provisioning-class-name: "queued-provisioning.gke.io"
    spec:
      subdomain: kr-headless-svc
      serviceAccountName: ray-worker
      terminationGracePeriodSeconds: 600
      containers:
      - name: gpu-job
        imagePullPolicy: Always 
        image: us-docker.pkg.dev/gkebatchexpce3c8dcb/llm/finetune:v0.1.25
        ports:
        - containerPort: 29500
        securityContext:
          privileged: true
        resources:
          requests:
            nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"
        command:
          - bash
          - -c
          - |
            accelerate launch \
            --config_file fsdp_config.yaml \
            --debug \
            --main_process_ip kr-finetune-gemma-7b-it-job-0.kr-headless-svc \
            --main_process_port 29500 \
            --machine_rank ${JOB_COMPLETION_INDEX} \
            --num_processes 2 \
            --num_machines 1 \
            fine_tune_gemma_7b_it.py
        env:
        - name: "BUCKET"
          value: "kr-finetune"
        - name: MODEL_NAME
          value: "google/gemma-1.1-7b-it"
        - name: NEW_MODEL
          value: "gemma-1.1-2b-it-chatbot"
        - name: MODEL_PATH
          value: "/model-data/model-kr"
        - name: EPOCHS
          value: "1"
        - name: NCCL_DEBUG
          value: "INFO"          
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /model-data
          readOnly: false
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: kr-finetune
            mountOptions: "implicit-dirs"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
        resource-type: gpu-a2
        pool-type: a2-2
      restartPolicy: OnFailure
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "ondemand"
        value: "true"
        operator: "Equal"
        effect: "NoSchedule"