apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gpu-metrics-gke-hpa
  namespace: _NAMEPSACE_ # your namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllm-openai
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metric:
        name: kubernetes.io|container|accelerator|duty_cycle
        selector:
          matchLabels:
            resource.labels.container_name: inference-server
            resource.labels.namespace_name: _NAMEPSACE_ # your namespace
      target:
        type: AverageValue
        averageValue:  $HPA_AVERAGEVALUE_TARGET