steps:
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: 
  - -c 
  - |
    gcloud container fleet memberships get-credentials ${_CLUSTER_NAME}
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - -c
  - |
    sed -i -e "s|J_ID|${_DATA_COMMIT}|g" yaml/provisioning-request-${_ACCELERATOR}.yaml
    sed -i -e "s|J_ID|${_DATA_COMMIT}|g" \
      -i -e "s|IMAGE_URL|${_IMAGE_TAG}|" \
      -i -e "s|V_TRAINING_DATASET_PATH|${_TRAINING_DATASET_PATH}|" \
      -i -e "s|V_MODEL_BUCKET|${_MODEL_BUCKET}|" \
      yaml/fine-tune-${_ACCELERATOR}-dws.yaml
  dir: "finetune-gemma"
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: 
  - -c
  - |
    kubectl apply -f yaml/provisioning-request-${_ACCELERATOR}.yaml -n ml-team
    kubectl apply -f yaml/fine-tune-${_ACCELERATOR}-dws.yaml -n ml-team
  dir: "finetune-gemma"
options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
