steps:
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: 
  - -c 
  - |
    gcloud container fleet memberships get-credentials mlp-kenthua
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args:
  - -c
  - |
    sed -i -e "s|J_ID|${_IMAGE_VERSION}|g" -i -e "s|IMAGE_URL|${_IMAGE_TAG}|" yaml/kh-fine-tune-l4.yaml
    sed -i -e "s|J_ID|${_IMAGE_VERSION}|g" yaml/kh-provisioningrequest-l4.yaml
  dir: "finetune-gemma"
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: "bash"
  args: 
  - -c
  - |
    kubectl apply -f yaml/kh-provisioningrequest-l4.yaml -n ml-team
    kubectl apply -f yaml/kh-fine-tune-l4.yaml -n ml-team
  dir: "finetune-gemma"
options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true