apiVersion: batch/v1
kind: Job
metadata:
  name: model-eval-J_ID
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: model-eval-job
    spec:
      serviceAccountName: ray-worker
      containers:
      - name: job
        image: IMAGE_URL
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - -c
        - |
          ACTION=predict python validate_fine_tuned_model.py
          ACTION=accuracy python validate_fine_tuned_model.py
        env:
        - name: "ENDPOINT"
          value: "V_ENDPOINT"
        - name: "MODEL_PATH"
          value: "V_MODEL_PATH"
        - name: "DATASET_TAG"
          value: "V_DATASET_TAG"
        - name: "BUCKET"
          value: "V_BUCKET"
        ##
        - name: "PROJECT_ID"
          value: "V_PROJECT_ID"
        - name: "PROMPT_MODEL_ID"
          value: "V_PROMPT_MODEL_ID"
        - name: "VERTEX_REGION"
          value: "V_VERTEX_REGION"
        resources:
          requests:
            cpu: "2"
            memory: "5Gi"
          limits:
            cpu: "2"
            memory: "5Gi"
      restartPolicy: Never

