apiVersion: batch/v1
kind: Job
metadata:
  name: ft-gemma-job-0
  namespace: ml-team  
spec:
  backoffLimit: 20
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: finetune-job
        job-track-id: ft-gemma-job-0
      annotations:
        gke-gcsfuse/volumes: "true"
        gke-gcsfuse/memory-limit: "35Gi"
        cluster-autoscaler.kubernetes.io/consume-provisioning-request: kh-a2-job
        cluster-autoscaler.kubernetes.io/provisioning-class-name: "queued-provisioning.gke.io"        
    spec:
      subdomain: headless-svc
      serviceAccountName: ray-worker
      terminationGracePeriodSeconds: 600
      containers:
      - name: gpu-job
        imagePullPolicy: Always 
        image: us-docker.pkg.dev/gkebatchexpce3c8dcb/llm/finetune:v0.1.44-nq-acc
        ports:
        - containerPort: 29500
        securityContext:
          privileged: true
        resources:
          requests:
            nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"
        command:
          - bash
          - -c
          - |
            accelerate launch \
            --config_file fsdp_config.yaml \
            --debug \
            --main_process_ip ft-gemma-job-0-0.headless-svc \
            --main_process_port 29500 \
            --machine_rank ${JOB_COMPLETION_INDEX} \
            --num_processes 2 \
            --num_machines 1 \
            fine_tune.py
        env:
        - name: "EXPERIMENT"
          value: "gemma-ft-hyperparam"
        - name: "BUCKET"
          value: "kh-finetune-ds"
        - name: MODEL_NAME
          value: "google/gemma-1.1-7b-it"
        - name: NEW_MODEL
          value: "gemma-1.1-7b-it-chatbot-0"
        - name: MODEL_PATH
          value: "/model-data/hyperparam/model-job-0"
        - name: NCCL_DEBUG
          value: "INFO"          
        - name: LORA_R
          value: "8"
        - name: LORA_ALPHA
          value: "16"
        - name: LORA_DROPOUT
          value: "0.1"
        - name: MAX_GRAD_NORM
          value: "1.0"
        - name: EPOCHS
          value: "2"
        - name: LEARNING_RATE
          value: "2e-5"
        - name: WEIGHT_DECAY
          value: ".01"
        - name: WARMUP_RATIO
          value: "0.1"
        - name: MAX_SEQ_LENGTH
          value: "1024"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: hf_api_token
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - name: gcs-fuse-csi-ephemeral
          mountPath: /model-data
          readOnly: false
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: kh-test-data
            mountOptions: "implicit-dirs"
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
        resource-type: gpu-a2
        pool-type: a2-2
      restartPolicy: OnFailure
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "ondemand"
        value: "true"
        operator: "Equal"
        effect: "NoSchedule"