apiVersion: batch/v1
kind: Job
metadata:
  generateName: module-download-job-
  namespace: default
  labels:
    app: model-downloader
spec:
  activeDeadlineSeconds: 7200
  backoffLimit: 2
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: 'true'
        gke-gcsfuse/memory-limit: 10Gi
        gke-gcsfuse/memory-request: 4Gi
    spec:
      containers:
        - name: dldr
          image: debian:latest
          command: ["/bin/sh", "-c"]
          args:
          - |
            apt-get update && apt-get install -y fuse2fs
            mkfs.ext4 -FF /dev/xvda
            fuse2fs -o fakeroot /dev/xvda /mnt
            # modify the next line
            cp -r /data/models/* /mnt
          volumeDevices:
          - name: data
            devicePath: /dev/xvda
          volumeMounts:
          - name: model-weights
            mountPath: /data/models
          securityContext:
            privileged: true
      restartPolicy: Never
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: block-pvc-model
        - name: model-weights
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: true
            volumeAttributes:
              bucketName: _YOUR_BUCKET_NAME_ # sed replace with your bucket name
              mountOptions: implicit-dirs
              gcsfuseLoggingSeverity: warning
              fileCacheCapacity: 40Gi