apiVersion: batch/v1
kind: Job
metadata:
  generateName: vllm-job-pvc-
  namespace: _NAMESPACE_  # replace with your namespace
  labels:
    app: vllm-job-pvc
    case-name: pvc-model-1024g
    model: _MODEL_NAME_  # replace with your model id
spec:
  activeDeadlineSeconds: 7200
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  template:
    metadata:
      labels:
        app: vllm-job-pvc
    spec:
      containers:
      - args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=2
        command:
        - python
        - -m
        - vllm.entrypoints.api_server
        env:
        - name: RUN_NAME
          value:  _MODEL_NAME_
        - name: MODEL_ID
          value: /data/models/_MODEL_ID_
        image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20240220_0936_RC01
        imagePullPolicy: IfNotPresent
        name: inference-server
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 25Gi
            memory: 25Gi
            nvidia.com/gpu: "2"
          requests:
            cpu: "2"
            ephemeral-storage: 25Gi
            memory: 25Gi
            nvidia.com/gpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /data/models
          name: model-weights
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-accelerator: _ACCELERATOR_TYPE_
      restartPolicy: Never
      schedulerName: default-scheduler
      tolerations:
      - key: "on-demand"
        value: "true"
        operator: "Equal"
        effect: "NoSchedule"
      - key: "nvidia/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: model-weights
        persistentVolumeClaim:
          claimName: pvc-model-weights-claim-1024gb-zone-a-ro
          readOnly: true