apiVersion: v1
kind: PersistentVolume
metadata:
  name: kh-models-disk-200gb-zone-hdml-a-1
  namespace: ml-team
  labels:
    user: kh
    pv-usage: model-cache-hdml-1
    pv-spec: hdml-200G
    pv-zone: us-east4-a
spec:
  storageClassName: "hyperdisk-ml"
  capacity:
    storage: 200Gi
  accessModes:
  - ReadOnlyMany
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/gkebatchexpce3c8dcb/zones/us-east4-a/disks/gemma2-9b-ft-hdml-200
    fsType: ext4
    readOnly: true
  mountOptions:
  - read_ahead_kb=4096
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - us-east4-a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-weight-disk-200gb-hdml-a-ro
  namespace: ml-team
spec:
  storageClassName: "hyperdisk-ml"
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      user: kh
      pv-usage: model-cache-hdml-1
      pv-zone: us-east4-a
